### ISSUE TITLE
sérialisation / désérialisation vector

### ISSUE THREAD

**Issue by matthieu-nesme** [Anatoscope/sofa#3]
- désérialisation des helper::vector pour soit faire comme maintenant, soit faire comme SVector si la string commence par [ (que ca soit capable de lire les 2 formats)
-sérialization des helper::vector pour faire comme SVector (puisque ca saura le lire, autant sérializer proprement)
- désérialization des SVector pour être capable de lire les sérializations actuelles des vectors (sans []) avec un gros warning (que ca soit capable de lire les 2 formats mais que la version sans [] soit là en secours avec un gros warning) - Peut-être pas utile mais ne mange pas de pain pour assurer compatibilité.
- revoir le binding de Node.createObject pour que les sequences se sérialise avec repr()

**Comment by matthieu-nesme** [comment]
@thomas-lemaire on peut fermer cette issue ?

**Comment by thomas-lemaire** [comment]
ouaip
